name: Run Code Checks
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install -g eslint@8.51.0
    - name: Install and run ESLint
      run: eslint . --quiet
    - name: Run Mocha Tests
      run: npm install && npm test
